-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.demos
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    phone_number character varying(20) NOT NULL,
    identity_number character varying(20) NOT NULL,
    tax_number character varying(20) NOT NULL,
    credit_cart_no character varying(20) NOT NULL,
    plate character varying(20) NOT NULL,
    PRIMARY KEY (id)
);
END;
